/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ContratosIndexRouteImport } from "./routes/contratos/index"
import { Route as OrgaosAgencyIdRouteImport } from "./routes/orgaos/$agencyId"
import { Route as FornecedoresSupplierIdRouteImport } from "./routes/fornecedores/$supplierId"
import { Route as ContratosContractIdRouteImport } from "./routes/contratos/$contractId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosIndexRoute = ContratosIndexRouteImport.update({
  id: "/contratos/",
  path: "/contratos/",
  getParentRoute: () => rootRouteImport,
} as any)
const OrgaosAgencyIdRoute = OrgaosAgencyIdRouteImport.update({
  id: "/orgaos/$agencyId",
  path: "/orgaos/$agencyId",
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresSupplierIdRoute = FornecedoresSupplierIdRouteImport.update({
  id: "/fornecedores/$supplierId",
  path: "/fornecedores/$supplierId",
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosContractIdRoute = ContratosContractIdRouteImport.update({
  id: "/contratos/$contractId",
  path: "/contratos/$contractId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/contratos/$contractId": typeof ContratosContractIdRoute
  "/fornecedores/$supplierId": typeof FornecedoresSupplierIdRoute
  "/orgaos/$agencyId": typeof OrgaosAgencyIdRoute
  "/contratos/": typeof ContratosIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/contratos/$contractId": typeof ContratosContractIdRoute
  "/fornecedores/$supplierId": typeof FornecedoresSupplierIdRoute
  "/orgaos/$agencyId": typeof OrgaosAgencyIdRoute
  "/contratos": typeof ContratosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/contratos/$contractId": typeof ContratosContractIdRoute
  "/fornecedores/$supplierId": typeof FornecedoresSupplierIdRoute
  "/orgaos/$agencyId": typeof OrgaosAgencyIdRoute
  "/contratos/": typeof ContratosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/contratos/$contractId"
    | "/fornecedores/$supplierId"
    | "/orgaos/$agencyId"
    | "/contratos/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/contratos/$contractId"
    | "/fornecedores/$supplierId"
    | "/orgaos/$agencyId"
    | "/contratos"
  id:
    | "__root__"
    | "/"
    | "/contratos/$contractId"
    | "/fornecedores/$supplierId"
    | "/orgaos/$agencyId"
    | "/contratos/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContratosContractIdRoute: typeof ContratosContractIdRoute
  FornecedoresSupplierIdRoute: typeof FornecedoresSupplierIdRoute
  OrgaosAgencyIdRoute: typeof OrgaosAgencyIdRoute
  ContratosIndexRoute: typeof ContratosIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contratos/": {
      id: "/contratos/"
      path: "/contratos"
      fullPath: "/contratos/"
      preLoaderRoute: typeof ContratosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/orgaos/$agencyId": {
      id: "/orgaos/$agencyId"
      path: "/orgaos/$agencyId"
      fullPath: "/orgaos/$agencyId"
      preLoaderRoute: typeof OrgaosAgencyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/fornecedores/$supplierId": {
      id: "/fornecedores/$supplierId"
      path: "/fornecedores/$supplierId"
      fullPath: "/fornecedores/$supplierId"
      preLoaderRoute: typeof FornecedoresSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contratos/$contractId": {
      id: "/contratos/$contractId"
      path: "/contratos/$contractId"
      fullPath: "/contratos/$contractId"
      preLoaderRoute: typeof ContratosContractIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContratosContractIdRoute: ContratosContractIdRoute,
  FornecedoresSupplierIdRoute: FornecedoresSupplierIdRoute,
  OrgaosAgencyIdRoute: OrgaosAgencyIdRoute,
  ContratosIndexRoute: ContratosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
